name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"   
          cache: maven

   
      - name: Build (Maven) – skip tests
        if: hashFiles('**/mvnw') != ''
        run: |
          chmod +x ./mvnw
          ./mvnw -B -DskipTests package

     
      - name: Build (Gradle) – skip tests
        if: hashFiles('**/gradlew') != ''
        run: |
          chmod +x ./gradlew
          ./gradlew assemble --no-daemon
